env: "local"
server:
  port: ":8080"
postgres:
  dsn: "postgres://user:password@localhost:5432/dbname?sslmode=disable"
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

telegram:
  token: "8572584315:AAFw41_OFsbvkvbuzpF9JXwWdSCRD1tw9Pw"
  chat_id: "860925468"
  
redis:
  addr: "localhost:6379"
  password: ""
  db: 0